title: ""
description: "Site personnel pour partager mes recherches, publications et enseignements."
author: "Farida Hamrani"
email: "farida.h1989@gmail.com"
baseurl: ""
url: "https://votre-site.com"
theme: minima
nav:
  - title: "Accueil"
    url: "/"
  - title: "Biographie"
    url: "/biographie"
  - title: "Publications"
    url: "/publications"
  - title: "Enseignement"
    url: "/enseignement"
  - title: "Projets"
    url: "/projets"
  - title: "Contact"
    url: "/contact"
