# _config.yml
title: "Farida Hamrani"
url: "https://hamranifarida.github.io"
baseurl: "/mon-site"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Correctif pour la navigation (ajoutez des slash finaux)
nav:
  - title: "Accueil"
    url: "/"
  - title: "Biographie"
    url: "/biographie/"
  - title: "Publications"
    url: "/publications/"
  - title: "Enseignement"
    url: "/enseignement/"
  - title: "Projets"
    url: "/projets/"
  - title: "Contact"
    url: "/contact/"
